services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $kernelBundles: '%kernel.bundles%'

    araise\TableBundle\:
            resource: '../../*'

    araise\TableBundle\EventListener\DoctrineOrderEventListener:
        tags:
            - { name: kernel.event_listener, event: araise_table.data_load.pre_load, method: orderResultSet, priority: 100 }

    araise\TableBundle\EventListener\ArrayOrderEventListener:
        tags:
            - { name: kernel.event_listener, event: araise_table.data_load.pre_load, method: orderResultSet, priority: 100 }

    araise\TableBundle\EventListener\FilterEventListener:
        tags:
            - { name: kernel.event_listener, event: araise_table.data_load.pre_load, method: filterResultSet, priority: 100 }

    araise\TableBundle\EventListener\SearchEventListener:
        tags:
            - { name: kernel.event_listener, event: araise_table.data_load.pre_load, method: searchResultSet, priority: 100 }

    araise\TableBundle\EventListener\AjaxFilterSearchListener:
      tags:
            - { name: kernel.event_listener, event: araise_ajax.result_request.filter_set, method: searchResultSet, priority: 100 }
            - { name: kernel.event_listener, event: araise_ajax.result_request.relation_set, method: searchResultSet, priority: 100 }

    araise\TableBundle\Manager\QueryBuilderManager:
        arguments:
            - !tagged_iterator 'araise_table.query_builder_provider'

    araise\TableBundle\Manager\FilterTypeManager:
        arguments:
            - !tagged_iterator 'araise_table.filter_type'

    _instanceof:
        araise\TableBundle\DataLoader\DataLoaderInterface:
            shared: false

        araise\TableBundle\Extension\ExtensionInterface:
            shared: false

    araise\TableBundle\Twig\TableTurboExtension:
        arguments: [ "%araise_table.enable_turbo%" ]
